### ISSUE TITLE
cytoscape-edgehandles

### ISSUE THREAD

**Issue by krpano-developer** [zakjan/cytoscape-mapbox-gl#5]
Hi @zakjan,
thanks for developing this wonderful code.
Is there a way to add an edge between nodes using cytoscape-edgehandles while in the leaflet map?
Thanks

**Comment by zakjan** [comment]
Hi, thanks for the appreciation. This cytoscape-mapbox-gl is expected to be compatible with cytoscape-edgehandles.

You may try to use the same approach with cytoscape-leaflet, and let @aleksplus know if it works or not. They are separate codebases. Let's follow up in https://github.com/aleksplus/cytoscape-leaflet/issues/2

**Comment by krpano-developer** [comment]
Thanks for the quick reply.
Sure, I will give it a try and let @aleksplus know if it works or not.
